#!/bin/sh
# Name this as pre-commit and copy to .git/hooks folder

# Get the name of the current branch
BRANCH_NAME=$(git symbolic-ref --short HEAD)

# Prevent commits to master branch
if [ "$BRANCH_NAME" = "master" ] || [ "$BRANCH_NAME" = "main" ]; then
  echo "Commits to the master branch are not allowed."
  echo " Please switch to another branch."
  exit 1
fi 
